stages:
    - format
    - env

variables:
    VENV: "/home/gitlab-runner/venv-native-layout-ci"
    GIT_SUBMODULE_STRATEGY: recursive


############################################################################################################
# Format

format_check:
    stage: format
    tags:
        - dev
    script:
        - source /home/spack/spack/share/spack/setup-env.sh
        - spack load --first llvm
        - find ./csrc -type f \( -name '*.cu' -o -name '*.cuh' -o -name '*.h' \) -exec clang-format --dry-run -Werror {} +


############################################################################################################
# Build

env_build_muxi:
    stage: env
    tags:
        - muxi
    script:
        - |
          docker run --rm --name muxi_layout_kernels-ci \
            --device=/dev/dri --device=/dev/mxcd --group-add video --privileged=true \
            --security-opt seccomp=unconfined --security-opt apparmor=unconfined --shm-size=100gb \
            --ulimit memlock=-1 \
            -v /usr/local/bin/grun:/usr/local/bin/grun:ro -v /tmp/gpu_locks:/tmp/gpu_locks \
            -v "$(pwd):/tmp/muxi_layout_kernels:ro" \
            maca-pytorch:3.0.0.4-torch2.6-py310-ubuntu24.04-amd64 \
            bash --login -c '
              mkdir -p /workspace
              cp -r /tmp/muxi_layout_kernels /workspace/muxi_layout_kernels
              cd /workspace/muxi_layout_kernels
              grun ./benchmark_and_test/test_all.sh
            '
